sudo: false
language: node_js

os:
  - linux
  - osx
node_js:
  - 10
  - 8
  - 6
  - 4

stages:
  - lint
  - works

jobs:
  include:
    - stage: lint
      script: echo lint

works:
  - stage: other
    script: echo hello

