language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    NUMPY=numpy
    CYTHON=cython
    MATPLOTLIB=matplotlib
    SYMPY=sympy
    H5PY=h5py
    SCIPY=scipy
    IPYTHON=ipython
    FASTCACHE=fastcache
    FLAKE8=flake8
    CODECOV=codecov
    COVERAGE=coverage
    PANDAS=pandas
    MOCK=mock
    NOSETIMER=nose-timer
    CODECOV=codecov

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip install --upgrade virtualenv
      python -m virtualenv venv
      source venv/bin/activate
      export PATH=/usr/lib/ccache:$PATH
    else
      brew update
      brew install ccache hdf5
      export PATH=/usr/local/opt/ccache/libexec:$PATH
    fi
    mkdir -p $HOME/.config/yt
    echo "[yt]" > $HOME/.config/yt/ytrc
    echo "suppressStreamLogging = True" >> $HOME/.config/yt/ytrc
    cat $HOME/.config/yt/ytrc
    cp tests/matplotlibrc .

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install $MOCK $NUMPY $SCIPY $H5PY $CYTHON $MATPLOTLIB $SYMPY $FASTCACHE $IPYTHON $FLAKE8 $CODECOV $COVERAGE $PANDAS $NOSE $NOSETIMER
    # install yt
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      pip install -e .
    fi

jobs:
  include:
    - stage: lint
      python: 3.6
      env: MOCK= NOSETIMER= NOSE= CODECOV= COVERAGE= NUMPY= CYTHON= MATPLOTLIB= SYMPY= H5PY= SCIPY= FASTCACHE= IPYTHON= PANDAS=
      script: flake8 yt/

    - stage: lint
      python: 2.7
      env: MOCK= NOSETIMER= NOSE= CODECOV= COVERAGE= NUMPY= CYTHON= MATPLOTLIB= SYMPY= H5PY= SCIPY= FASTCACHE= IPYTHON= PANDAS=
      script: flake8 yt/


    - stage: tests
      name: "PY 2.7 Unit Test"
      python: 2.7
      script: flake8 yt/

    - stage: tests
      python: 3.5
      name: "PY 3.5 Unit Test"
      script: flake8 yt/

    - stage: tests
      python: 3.6
      name: "PY 3.6 Unit Test"
      script: flake8 yt/

    - stage: tests
      os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
      script: flake8 yt/

after_success:
  - |
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      codecov
    fi
