language: python
sudo: required
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/test_data_cache

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    NUMPY=numpy
    CYTHON=cython
    MATPLOTLIB=matplotlib
    SYMPY=sympy
    H5PY=h5py
    SCIPY=scipy
    IPYTHON=ipython
    FASTCACHE=fastcache
    FLAKE8=flake8
    CODECOV=codecov
    COVERAGE=coverage
    PANDAS=pandas
    MOCK=mock
    NOSETIMER=nose-timer
    REQUESTS=requests
    YAML=pyyaml

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip install --upgrade virtualenv
      python -m virtualenv venv
      source venv/bin/activate
      export PATH=/usr/lib/ccache:$PATH
    else
      brew update
      brew install ccache hdf5
      export PATH=/usr/local/opt/ccache/libexec:$PATH
    fi
    mkdir -p $HOME/.config/yt
    echo "[yt]" > $HOME/.config/yt/ytrc
    echo "suppressStreamLogging = True" >> $HOME/.config/yt/ytrc
    echo "test_data_cache_dir = $HOME/test_data_cache" >> $HOME/.config/yt/ytrc
    echo "test_data_dir = $HOME/test_data" >> $HOME/.config/yt/ytrc
    cat $HOME/.config/yt/ytrc
    cp tests/matplotlibrc .

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install $MOCK $NUMPY $SCIPY $H5PY $CYTHON $MATPLOTLIB $SYMPY $FASTCACHE $IPYTHON $FLAKE8 $CODECOV $COVERAGE $PANDAS $NOSE $NOSETIMER $REQUESTS $YAML
    # install yt
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      pip install -e .
    fi

jobs:
  include:
    - stage: tests
      name: "Python: 2.7 Answer Tests"
      python: 2.7
      env: NUMPY=numpy==1.10.4 CYTHON=cython==0.24 MATPLOTLIB=matplotlib==1.5.3 SYMPY=sympy==1.0 H5PY= SCIPY= FASTCACHE= FLAKE8= IPYTHON=ipython==1.0
      script:
        - python tests/download_datasets.py
        - coverage run $(which nosetests) -c nose_answer.cfg
      after_failure: python tests/report_failed_answers.py -f -m --xunit-file "answer_nosetests.xml"

    - stage: tests
      name: "Python: 3.6 Answer Tests 1"
      python: 3.6
      env: FLAKE8= 
      script:
      - python tests/download_datasets.py
      - ls -lta -R $HOME/test_data
      - coverage run $(which nosetests) -c nose_answer.cfg
      after_failure: python tests/report_failed_answers.py -f -m --xunit-file "answer_nosetests.xml"

    - stage: tests
      name: "Python: 3.6 Answer Tests 2"
      python: 3.6
      env: FLAKE8=
      script:
      - python tests/download_datasets.py
      - ls -lta -R $HOME/test_data
      - nosetests --with-answer-testing --nologcapture -d -vv -s --with-xunit --xunit-file "answer_nosetests.xml" --local --local-dir=answer-store --with-timer yt/visualization/tests/test_raw_field_slices.py

    - stage: tests
      name: "Python: 3.6 Answer Tests 3"
      python: 3.6
      env: FLAKE8=
      script:
      - python tests/download_datasets.py
      - ls -lta -R $HOME/test_data
      - nosetests --with-answer-testing --nologcapture -d -vv -s --with-xunit --xunit-file "answer_nosetests.xml" --local --local-dir=answer-store --attr "answer_test" --with-timer yt/visualization/tests/test_raw_field_slices.py

after_success:
  - |
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      codecov
    fi
