language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    NUMPY=numpy
    CYTHON=cython
    MATPLOTLIB=matplotlib
    SYMPY=sympy
    H5PY=h5py
    SCIPY=scipy
    IPYTHON=ipython
    FASTCACHE=fastcache
    FLAKE8=flake8
    CODECOV=codecov
    COVERAGE=coverage

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip install --upgrade virtualenv
      python -m virtualenv venv
      source venv/bin/activate
      export PATH=/usr/lib/ccache:$PATH
    else
      brew update
      brew install ccache hdf5
      export PATH=/usr/local/opt/ccache/libexec:$PATH
    fi
    mkdir -p $HOME/.config/yt
    echo "[yt]" > $HOME/.config/yt/ytrc
    echo "suppressStreamLogging = True" >> $HOME/.config/yt/ytrc
    cat $HOME/.config/yt/ytrc
    mkdir $HOME/.config/matplotlib
    mv matplotlibrc $HOME/.config/matplotlib/

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install mock $NUMPY $SCIPY $H5PY $CYTHON $MATPLOTLIB $SYMPY $FASTCACHE $IPYTHON $FLAKE8 $CODECOV $COVERAGE nose nose-timer
    # install yt
    pip install -e .
    
jobs:
  include:
    - stage: tests
      python: 2.7
      env: NUMPY=numpy==1.10.4 CYTHON=cython==0.24 MATPLOTLIB=matplotlib==1.5.3 SYMPY=sympy==1.0 H5PY= SCIPY= FASTCACHE= FLAKE8= IPYTHON=ipython==1.0
      script: 
      - python check_matplotlib.py
      - echo $HOME
      - cat /home/travis/build/git-abhishek/master_testing_yt/venv/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
      - coverage run $(which nosetests) -c nose.cfg visualization/tests/test_color_maps.py
      - python check_matplotlib.py

    - stage: tests
      python: 3.4
      env: FLAKE8=
      script: 
      - python check_matplotlib.py
      - echo $HOME
      - cat /home/travis/build/git-abhishek/master_testing_yt/venv/lib/python3.4/site-packages/matplotlib/mpl-data/matplotlibrc
      - coverage run $(which nosetests) -c nose.cfg visualization/tests/test_color_maps.py
      - python check_matplotlib.py

    - stage: tests
      python: 3.5
      env: FLAKE8=
      script:  
      - python check_matplotlib.py
      - echo $HOME
      - cat /home/travis/build/git-abhishek/master_testing_yt/venv/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
      - coverage run $(which nosetests) -c nose.cfg visualization/tests/test_color_maps.py
      - python check_matplotlib.py

    - stage: tests
      python: 3.6
      env: FLAKE8=
      script:
      - python check_matplotlib.py
      - echo $HOME
      - cat /home/travis/build/git-abhishek/master_testing_yt/venv/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
      - coverage run $(which nosetests) -c nose.cfg visualization/tests/test_color_maps.py
      - python check_matplotlib.py

    - stage: tests
      os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
      script:  
      - python check_matplotlib.py
      - echo $HOME
      - cat /usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
      - coverage run $(which nosetests) -c nose.cfg visualization/tests/test_color_maps.py
      - python check_matplotlib.py

after_success:
  - codecov
