# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\Miniconda36-x64"

  matrix:
      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "2.7"

  APPVEYOR: true
  APPVEYOR_CLOUDINARY_NAME:
    secure: dp56jJ9SBNJ4BxxZvIhXCA==
  APPVEYOR_CLOUDINARY_API_KEY:
    secure: /50oWcIu2obOklQ4SLyKDg==
  APPVEYOR_CLOUDINARY_API_SECRET:
    secure: /0ksxQKYNGPwCRazEKEMemGdYVPYYq506CrYRl7x7H8=
    

platform:
    -x64

install:
    - "if not exist \"%userprofile%\\.config\\yt\" mkdir %userprofile%\\.config\\yt"
    - "echo [yt] > %userprofile%\\.config\\yt\\ytrc"
    - "echo suppressStreamLogging = True >> %userprofile%\\.config\\yt\\ytrc"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    # Create a conda environment
    - "conda update -q --yes conda"
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install --yes -c conda-forge numpy scipy nose setuptools ipython Cython sympy fastcache h5py matplotlib mock coverage nose-timer pyyaml"
    - "pip install -e ."
    - "pip install cloudinary"

# Not a .NET project
build: false

test_script:
  # - "coverage run -a tests/nose_runner.py -r"
  - "nosetests --nologcapture -sv yt"

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
